---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  namespace: logging
  labels:
    app: elasticsearch
spec:
  storageClassName: logging-storage
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/installer/logging/storage/elasticsearch"
