---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: logging
  labels:
    app: elasticsearch
spec:
  storageClassName: logging-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

