---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  ports:
    - port: 5601
      nodePort: 32561
  selector:
    app: kibana
  type: NodePort
