---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.2.0
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        env:
          - name: ELASTICSEARCH_URL
            #value: http://elasticsearch:9200
            value: http://elasticsearch.logging.svc.cluster.local:9200
        ports:
        - containerPort: 5601
