apiVersion: v1
kind: PersistentVolume
metadata:
  name: fluentd-vldc-pv
  namespace: logging
  labels:
    app: fluentd
spec:
  storageClassName: logging-storage
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: logging
    name: fluentd-vldc-pvc
  hostPath:
    path: "/var/lib/docker/containers"
