kubectl delete -f 15.fluentd_ds.yaml 
kubectl delete -f 14.fluentd_crb.yaml 
kubectl delete -f 13.fluentd_cr.yaml 
kubectl delete -f 12.fluentd_sa.yaml 
#kubectl delete -f 11.fluentd_vldc_pvc.yaml 
#kubectl delete -f 10.fluentd_vldc_pv.yaml 
#kubectl delete -f 09.fluentd_vl_pvc.yaml 
#kubectl delete -f 08.fluentd_vl_pv.yaml 
kubectl delete -f 07.kibana_d.yaml 
kubectl delete -f 06.kibana_svc.yaml
kubectl delete -f 05.es_ss.yaml 
kubectl delete -f 04.es_svc.yaml 
kubectl delete -f 03.es_pvc.yaml 
kubectl delete -f 02.es_pv.yaml 
#kubectl delete -f 01.logging_cs.yaml 
#kubectl delete -f 00.logging_ns.yaml
