---
apiVersion: v1
kind: Service
metadata:
  name: fluentd-ui
  namespace: logging
  labels:
    app: fluentd-ui
spec:
  ports:
    - port: 9292
      nodePort: 32562
  selector:
    app: fluentd-ui
  type: NodePort
