apiVersion: v1
kind: PersistentVolume
metadata:
  name: tomcat-pv
  namespace: tomcat
  labels:
    app: tomcat
spec:
  storageClassName: tomcat-storage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany 
  hostPath:
    path: "/home/installer/tomcat/storage/webapps"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tomcat-pv-logs
  namespace: tomcat
  labels:
    app: tomcat
spec:
  storageClassName: tomcat-storage
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/installer/tomcat/storage/logs"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tomcat-pv-lib
  namespace: tomcat
  labels:
    app: tomcat
spec:
  storageClassName: tomcat-storage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/installer/tomcat/storage/lib"
