apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-local-pvc
  namespace: tomcat
spec:
  storageClassName: tomcat-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-local-pvc-logs
  namespace: tomcat
spec:
  storageClassName: tomcat-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-local-pvc-lib
  namespace: tomcat
spec:
  storageClassName: tomcat-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
