apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tomcat-storage
  namespace: tomcat
  #annotations:
  #  storageclass.kubernetes.io/is-default-class: "true"
provisioner: microk8s.io/hostpath
volumeBindingMode: Immediate
