apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool
  namespace: pgpool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgpool
  template:
    metadata:
      labels:
        app: pgpool
    spec:
      containers:
      - name: pgpool
        image: pgpool/pgpool:4.1
        command: ["sh", "-c", "$PGPOOL_BINARY_DIR/pgpool -n -f $PGPOOLCONF -F $PCP_CONF -a $POOL_HBA_CONF"]
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: hot-postgres-auth
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hot-postgres-auth
              key: POSTGRES_PASSWORD
        - name: PGPOOL_PARAMS_BACKEND_HOSTNAME0
          value: "hot-postgres"
        - name: PGPOOL_PARAMS_BACKEND_HOSTNAME1
          value: "hot-postgres-replicas"
        - name: PGPOOL_PARAMS_BACKEND_APPLICATION_NAME0
          value: "hot-postgres"
        - name: PGPOOL_PARAMS_BACKEND_APPLICATION_NAME1
          value: "hot-postgres-1"
        volumeMounts:
        - name: pgpool-config
          mountPath: /usr/local/pgpool-II/etc
      - name: pgpool-stats
        image: pgpool/pgpool2_exporter:1.0 
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: hot-postgres-auth
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hot-postgres-auth
              key: POSTGRES_PASSWORD
        - name: PGPOOL_SERVICE
          value: "localhost"
      volumes:
      - name: pgpool-config
        configMap:
          name: pgpool-config
---
apiVersion: v1
kind: Service
metadata:
  name: pgpool
  namespace: pgpool
spec:
  selector:
    app: pgpool
  ports:
  - name: pgpool-port
    protocol: TCP
    port: 9999
    targetPort: 9999
    nodePort: 31852
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: pgpool-stats
  namespace: pgpool
  labels:
    app: pgpool-stats
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9719"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: pgpool
  ports:
  - name: pgpool-stats-port
    protocol: TCP
    port: 9719
    targetPort: 9719

