apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rabbitmq-storage
  namespace: rabbitmq
  #annotations:
  #  storageclass.kubernetes.io/is-default-class: "true"
provisioner: microk8s.io/hostpath

