kubectl apply -f 01.storageClass.yaml
kubectl apply -f 02.pv.yaml
kubectl apply -f secret.yaml
kubectl apply -f secret2.yaml
kubectl apply -f secret3.yaml
kubectl apply -f service.yaml
kubectl apply -f service2.yaml
kubectl apply -f ServiceAccount.yaml
kubectl apply -f role.yaml
kubectl apply -f rolebinding.yaml
kubectl apply -f configmap.yaml
kubectl apply -f configmap2.yaml
kubectl apply -f statefulset.yaml
