apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: rabbitmq-ha
  name: rabbitmq-rabbitmq-ha
  namespace: rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbitmq-rabbitmq-ha
subjects:
- kind: ServiceAccount
  name: rabbitmq-rabbitmq-ha
  namespace: rabbitmq

