apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq-ha
  name: rabbitmq-rabbitmq-ha-discovery
  namespace: rabbitmq
spec:
  ports:
  - name: http
    port: 15672
    protocol: TCP
    targetPort: http
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: amqp
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: epmd
  publishNotReadyAddresses: true
  selector:
    app: rabbitmq-ha
    release: rabbitmq
  sessionAffinity: None
  type: ClusterIP

