apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: rabbitmq
  secrets:
  - name: default-token-2fqz8
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    labels:
      app: rabbitmq-ha
      release: rabbitmq
    name: rabbitmq-rabbitmq-ha
    namespace: rabbitmq
  secrets:
  - name: rabbitmq-rabbitmq-ha-token-kxfrr
kind: List
metadata: {}

