apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: pgadmin
    app.kubernetes.io/managed-by: Helm
    chart: pgadmin-0.1.12
    heritage: Helm
    release: pgadmin
  name: jaeger-pvc-volume
  namespace: istio-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: jaeger-storage
  volumeMode: Filesystem
