---
apiVersion: v1
kind: Namespace
metadata:
  name: wildfly
  labels:
    app: wildfly
---
apiVersion: v1
kind: Service
metadata:
  name: wildfly-nodeport
  namespace: wildfly
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30300
    - name: management
      port: 9990
      targetPort: 9990
      nodePort: 30301
    - name: https
      port: 8443
      targetPort: 8443
  selector:
    app: wildfly
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wildfly-pvc
  namespace: wildfly
spec:
  storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
