apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: nginx
  labels:
    app: nginx
spec:
  storageClassName: nginx-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany 
  hostPath:
    path: "/home/installer/nginx/storage/html"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-logs
  namespace: nginx
  labels:
    app: nginx
spec:
  storageClassName: nginx-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/installer/nginx/storage/logs"
