apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: nginx
spec:
  storageClassName: nginx-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-logs
  namespace: nginx
spec:
  storageClassName: nginx-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
