apiVersion: v1
kind: PersistentVolume
metadata:
  name: hot-postgres-pv-02
  namespace : pgpool
  labels:
    type: local
spec:
  storageClassName: pgpool-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hot-postgres-02"
