apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: hot-postgres
  namespace: pgpool
spec:
  version: "11.2"
  replicas: 3
  standbyMode: Hot
  databaseSecret:
    secretName: hot-postgres-auth
  storageType: Durable
  storage:
    storageClassName: pgpool-storage
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitor:
    agent: prometheus.io/builtin
