apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv-volume
  namespace : pgpool
  labels:
    type: local
spec:
  storageClassName: pgadmin-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pgadmin"
