apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgpool-pv-claim
  namespace: pgpool
spec:
  storageClassName: pgpool-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
