apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgpool-pv-volume
  namespace : pgpool
  labels:
    type: local
spec:
  storageClassName: pgpool-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pgpool"
