apiVersion: v1
kind: Service
metadata:
  name: pzoo
  namespace: kafka
spec:
  ports:
  - port: 2888
    targetPort: 2888
    name: peer
  - port: 3888
    targetPort: 3888
    name: leader-election
  selector:
    app: zookeeper
    storage: persistent
