apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper
  namespace: kafka
  labels:
    app: zookeeper
spec:
  storageClassName: kafka-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/installer/kafka/storage/zookeeper"
