apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper
  namespace: kafka
spec:
  storageClassName: kafka-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
