apiVersion: v1
kind: Namespace
metadata:
  name: hazelcast 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-cluster
  namespace: hazelcast 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: default 
  namespace: hazelcast
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-configuration
  namespace: hazelcast
data:
  hazelcast.yaml: |-
    hazelcast:
      cluster-name: cluster 
      network:
        join:
          multicast:
            enabled: false 
          kubernetes:
            enabled: true 
            namespace: hazelcast
            service-name: hazelcast-cluster
        rest-api:
          enabled: true
          endpoint-groups:
            HEALTH_CHECK:
              enabled: true
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast
  namespace: hazelcast
  labels:
    app.kubernetes.io/name: hazelcast
spec:
  replicas: 3
  serviceName: hazelcast 
  selector:
    matchLabels:
      app.kubernetes.io/name: hazelcast
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hazelcast
    spec:
      terminationGracePeriodSeconds: 600
      containers:
      - name: hazelcast
        image: hazelcast/hazelcast:4.1.2
        ports:
        - name: hazelcast
          containerPort: 5701
        livenessProbe:
          httpGet:
            path: /hazelcast/health/node-state
            port: 5701
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /hazelcast/health/node-state
            port: 5701
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - name: hazelcast-storage
          mountPath: /data/hazelcast
        env:
        - name: JAVA_OPTS
          value: "-Dhazelcast.config=/data/hazelcast/hazelcast.yaml -Dhazelcast.diagnostics.enabled=true -Dhazelcast.shutdownhook.policy=GRACEFUL -Dhazelcast.graceful.shutdown.max.wait=600"
      volumes:
      - name: hazelcast-storage
        configMap:
          name: hazelcast-configuration
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hz-pv
  namespace: hazelcast
spec:
  storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-center
  namespace: hazelcast 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: management-center 
  template:
    metadata:
      labels:
        app: management-center
    spec:
      containers:
      - name: hazelcast
        image: hazelcast/management-center:4.2021.03
---
kind: Service
apiVersion: v1
metadata:
  name: hazelcast-cluster 
  namespace: hazelcast 
spec:
  type: NodePort 
  selector:
    app.kubernetes.io/name: hazelcast
  ports:
  - name: hazelcast
    port: 5701
    nodePort: 30010 
---
kind: Service
apiVersion: v1
metadata:
  name: management-center-svc 
  namespace: hazelcast 
spec:
  type: NodePort
  selector:
    app: management-center
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30009

